import turtle
turtle.shape ('turtle')
square=turtle.clone()
square.shape('square')
square.penup()
square.goto(50, 50)
square.pendown()
square.goto(50, 0)
square.goto(100, 0)
square.goto (100, 50)
square.goto(50, 50)
triangle=turtle.clone()
triangle.shape ('triangle')
triangle.penup()
triangle.goto(-50, 0)
triangle.pendown()
triangle.goto(-100, 0)
triangle.goto(-100, 50)
triangle.goto(-50, 0)

square=turtle.clone()
square.shape('square')
square.penup()
square.goto(50, 0)
square=turtle.clone()
square.shape('square')
square.penup()
square.goto(100, 0)
square=turtle.clone()
square.shape('square')
square.penup()
square.goto(100, 50)

triangle=turtle.clone()
triangle.shape ('triangle')
triangle.penup()
triangle.goto(-100, 0)

triangle=turtle.clone()
triangle.shape ('triangle')
triangle.penup()
triangle.goto(-100, 50)


turtle.mainloop()
